language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: agile-basin-31621
  api_key:
    secure: c/emBX1wTAFdBYnHDzbVgG9rveFetwYkcrXzZpThW+KGanbnfVkDyWF6tL+LvIZ9P/9v+8CM48GUlg8FQEq7bItCN0LXmP4dK3+orOBZNZhUC/ZzBA05kcdm8D5q8i3t4nTsSV9dLemkTFXPjL6oDWe6od3xGDvt+rMcwkasRh/H1TiGq9qOVxQ2rhE/GEBj2loMHNXTSs4ND0WA4TbTVZOEGgtsTKjINvNHXaOqgCDXUZNa290o2w9wgvC6q3MdBuM99ntOG33+83THVY79y3oeMF2LP2ilwRYbcnQE4v0mFriOloqlNK5TCN8udXX9MGSfNCq5+xx0n1h+JfAXt2y4nSV2CMnvH7EUKG0JKgo2ajSKj+qsS8iYQGUrkaocQe8hORJ4cS/8uLQkBE0VztrcGChTjnf3PlaW3vKS1GK1Pu5Wkam/iaiI3hQhGir3VLV1pA1vmpIaPtZBruPwZEmDPQwmCNp1mEFNskYCk3eMvK1qq7tj8kbaS0Ly+S70O006t1qgYZMX7PIvFdJHx4igGTGUUising/VfsTdXaaQzVNszR91JyAvIoSO1KLItHPQ8Hp/vHpVx7qcxBlPJadqBJMplVIyviUHXX+GpzUJy/MENvVzzTvOLH8vPIKqpBZvezPHckpDB/8MxhOKdAqR03F6kjYXzHAN7P+KbVA=
