language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: agile-basin-31621
  api_key:
    secure: j7tky0mb0dapzXeCp98nplWNt41vWyH3fqt0cbWJ+PS4ljcgiLdSkiCNRzJhRFEcfQwMC/2fUFyvKHf5OVRwRkyr2AEX3xt4BFDLRJp9InGlphQM1vx7hG5izoF8ce/OkwAV1Fbrrakim/oUM1YiML2Un1wylBtg5HjQfrxR7LulZ1mGZ65/vcXA9k5eX2ktpwwekNZ2P7RtEQIRB7Vz9kClWKwrHgSHZCz4AYm8dtx7NGF7+uJ3VWIscWeFNVsIQ14Dn++WeWYEQaPqUJEWVQXEzkAiMdB2NtbwyJVSg4eTL+3UUtYxRHZT4P5sfGdL/EdPW/Aa/MvE5+C6z+mQZ9keiNMPPyAB8oSiIz7l2KgJDdhzBtCIigpiU2Jcix6rYgGYTdJdQz5Tq3pK5YdXsYrWjplLYJzNpBgU6ve0MLOiMjzWVbTKBEj1qiBbRB+CNlTh1/VsrsIrD1PjGckdV+eHHIddtx588eVlvLvIKlcw4+fKBbJBOSlHEGMwndU/iBw6NTSdB7bUGTqtd3i+g2PkdoiMY4Ai23h195x2UYTkcwamiQvN/l+Yj1/CmjsXU0tcNagp5twUYCFjBji8W/bCz4rkUKmWOaWbIEp3pGV2zzzBNTsqTL267SAuWkxoj2KwCVT0x/cra3rWTKpu0nU7aDy16wD9IPRmm24C2DA=
