language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: agile-basin-31621
  api_key:
    secure: afCZWaImxDAWCFbgMY07upPPHtM4tbuZYv7wHel4CDTsltoyoDG8ecX7rY4mSPA/r9EeJQsZFwyNA2s5jCIHqoO86S4VBvWXusMl9eOjM0Oivhx5LujF95nNtwGSE9GznJionxkcv8Mo4yF6d6YM1ILlrzC/297eOr0VekIFyTI03IGPYULKHE1XJAsFZbgrFialOJ9tIsvTQl2L63+0iktEpLECEy/1RMZKnCX45VF+X2Rh8CZ3YkSPSdxna/41yAp3aRGgXMaLCjVSL6NX9swOaz5NKDdlJsdKiOPuGMOXApiXul01OJnblZOWINBdzPcnDz5YFO3bTewNijGM4K7HrKeJLUZmS2Rchi8Do9FiBz4tHRjGW3ZzBqq2HiQw1dzoSqShJQoTjkOf6mfY66ighK497G/WpWW1LzoyQ3rlq6Lcn803MZ2bIorSGIO7b6IzBRtXFXIrcKV+7nwT+skekn/aqnEB6COIXchePQ85UoD+LNmqNrHmpwaWzf4OiQsUpDgmT7W3NoXunfHzogFwFrNkpF2OcEyaEIT6gUwiUln+1Q8PQx5V30P/UwUuThCPUJcIvwSEzr7erz9uU+3bzZSI3uJNwWnRaUvS52KbpxzLeW8UI0xsrjDplrHIWMwqCYcqtluCOkhS+BLg0OFThqEQEk+KVAC8yvAp0lc=
